# Generated by Django 3.1.6 on 2021-04-16 19:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='nil'),
            preserve_default=False,
        ),
    ]
